### PR TITLE
Cleaned up SMART spacing

### PR DESCRIPTION
**Pull request by hr0bdn8u**

### CODE REVIEW

**Comment by louwrentius** [comment]
Hi, thanks for your contribution!
I've noticed that you basically removed all the various hard-coded spacing, which if not required would be amazing. I will have to test this myself first on Debian and Ubuntu to see if it does still work properly.

**Comment by hr0bdn8u** [comment]
I've been running your showtools for years without problems. Earlier this year i made this minor formatting change at home (Slackware 14.2) because one of my new drives was not showing it's smart info correctly in your output. 

At home I'm running the following drives:
1 x Samsung SSD 850 EVO 250GB
3 x Seagate EXOS 16TB (ST16000NM001G-2K)
1 x WDC WD80EZAZ-11T

Let me know if you have any further questions. :-)

**Comment by louwrentius** [comment]
Hi, maybe can you share which version of smartmontools you are running? I'm afraid your patch would break smartmontools on other platforms.

**Comment by hr0bdn8u** [comment]
I'm running showtools on both an older Slackware 14.2 (Samsung EVO SSD, Seagate EXOS, 1 WD RED) and on a very recent Proxmox (Debian 12) (WD RED) release. In both cases the slight change works for the respective drives.

Slackware:
```
# cat /etc/slackware-version
Slackware 14.2
# uname -a
Linux darkstar4 4.4.301 #2 SMP Mon Jan 31 20:28:17 CST 2022 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
# smartctl -V | head -1
smartctl 6.5 2016-05-07 r4318 [x86_64-linux-4.4.301] (local build)
# ~/bin/showtools/show -E disk -SstrRPHCu | sed '/^\s*$/d' | cut -b 3-
Dev   Serial Number     GB      Temp   Hours   PS   RS   RSE   CRC   Spin
sda   XXXXXXXXXXXXXXX   250     30     55113   ?    0    ?     ?     ?
sdb   XXXXXXXX          16001   33     3916    0    0    ?     0     6
sdc   XXXXXXXX          16001   34     3942    0    0    ?     0     6
sdd   XXXXXXXX          16001   37     4276    0    0    ?     0     8
sde   XXXXXXXX          8002    34     40041   0    0    0     0     39
```

Debian 12.2:
```
# cat /etc/debian_version
12.2
# uname -a
Linux pve 6.2.16-19-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-19 (2023-10-24T12:07Z) x86_64 GNU/Linux
# smartctl -V | head -1
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.2.16-19-pve] (local build)
# ./show -E disk -SstrRPHCu | sed '/^\s*$/d' | cut -b 3-
Dev       Serial Number   GB     Temp   Hours   PS   RS   RSE   CRC   Spin
nvme0n1                   256    ?      ?       ?    ?    ?     ?     ?
sda       XXXXXXXX        8002   34     44879   0    0    0     0     50
sdb       XXXXXXXX        8002   32     43521   0    0    0     0     46
sdc       XXXXXXXX        8002   36     44879   0    0    0     2     49
sdd       XXXXXXXX        8002   32     44879   0    0    0     0     50
sde       XXXXXXXX        8002   35     51242   0    0    0     75    59

```
Let me know if you need anything else.

**Comment by louwrentius** [comment]
I've started working on a new version that uses the JSON output of smartctl so all this string parsing isn't required anymore. It may take a bit but some JSON parsing is already implemented and pushed to the development branch although it's still a work in progress.

**Comment by louwrentius** [comment]
If you want, you can try the latest release and see if it works on slackware.

**Pull request closed without merging**
